### ISSUE TITLE
Repository Permissions

### ISSUE THREAD

**Issue by isteiger** [PinkertonMC/s3_resourcepack#1]
I don't think it should be public yet. This is up to you, though.

**Comment by asavage7** [comment]
It needs to be as i'm using this as the source for the server resource pack.

**Comment by isteiger** [comment]
You can get it to work, you just need to authenticate with git.

**Comment by asavage7** [comment]
yeah but that's kinda out of the scope of this project. I'll look at it later though.

**Comment by isteiger** [comment]
its pretty easy but aight
